from OpenGL.GL import *
from OpenGL.GLUT import *
from OpenGL.GLU import *
from midpoint_line import *

def logo():
    glColor3f(1.0, 0.0, 0.0)
    sx,sy=(50,450)
    height,width,height_1=50,400,50
    Box_left=(sx,sy,sx,sy-height)#Box Plotting
    drawLine(Box_left[0],Box_left[1],Box_left[2],Box_left[3])
    Box_right=(sy+height_1,sy,sy+height_1,sy-height)
    drawLine(Box_right[0], Box_right[1], Box_right[2], Box_right[3])
    Box_top = (sx,sy,sy+height_1,sy)#Box Plotting
    drawLine(Box_top[0], Box_top[1], Box_top[2], Box_top[3])
    Box_bottom = (sx, sy-height,sy+height_1,sy-height)
    drawLine(Box_bottom[0], Box_bottom[1], Box_bottom[2], Box_bottom[3])
    glColor3f(1.0, 1.0, 0.0)
    sx,sy=(60,440)
    height,width=(20,10)
    A_left=(sx,sy,sx,sy-height)#Plotting A
    drawLine(A_left[0],A_left[1],A_left[2],A_left[3])
    A_right = (sx+width, sy, sx+width, sy - height)
    drawLine(A_right[0], A_right[1], A_right[2], A_right[3])
    A_top = (sx , sy, sx + width,sy)
    drawLine(A_top[0], A_top[1], A_top[2], A_top[3])
    A_middle = (sx, sy-width, sx + width, sy-width)
    drawLine(A_middle[0], A_middle[1], A_middle[2], A_middle[3])
    glColor3f(1.0, 0.0, 1.0)
    sx, sy = (80, 440)
    height, width = (20, 10)
    R_left = (sx,sy, sx,sy-height)#Plotting R
    drawLine(R_left[0],R_left[1],R_left[2],R_left[3])
    R_right = (sx+width, sy, sx+width, sy - width)
    drawLine(R_right[0], R_right[1], R_right[2], R_right[3])
    R_top = (sx, sy, sx + width, sy)
    drawLine(R_top[0], R_top[1], R_top[2], R_top[3])
    R_middle = (sx , sy-width, sx + width, sy - width)
    drawLine(R_middle[0], R_middle[1], R_middle[2], R_middle[3])
    R_diagonal = (sx, sy - width, sx + width, sy - height)
    drawLine(R_diagonal[0], R_diagonal[1], R_diagonal[2], R_diagonal[3])
    glColor3f(1.0, 1.0, 1.0)
    sx, sy = (100, 440)
    height, width = (20, 10)
    C_left=(sx,sy,sx,sy-height)# Plotting C
    drawLine(C_left[0],C_left[1],C_left[2],C_left[3])
    C_top = (sx, sy, sx+width, sy)
    drawLine(C_top[0], C_top[1], C_top[2], C_top[3])
    C_bottom = (sx, sy-height, sx + width, sy-height)
    drawLine(C_bottom[0], C_bottom[1], C_bottom[2], C_bottom[3])
    glColor3f(0.0, 0.0, 1.0)
    sx, sy = (120, 440)
    height, width = (20, 10)
    H_left = (sx, sy, sx , sy - height)# Plotting H
    drawLine(H_left[0], H_left[1], H_left[2], H_left[3])
    H_right = (sx+width, sy, sx+width, sy - height)
    drawLine(H_right[0], H_right[1], H_right[2], H_right[3])
    H_middle = (sx , sy-width, sx + width, sy - width)
    drawLine(H_middle[0], H_middle[1], H_middle[2], H_middle[3])
    glColor3f(1.0, 0.0, 0.5)
    sx, sy = (140, 440)
    height, width = (20, 10)
    E_left = (sx, sy, sx, sy - height)  # Plotting E
    drawLine(E_left[0], E_left[1], E_left[2], E_left[3])
    E_top = (sx, sy, sx + width, sy)
    drawLine(E_top[0], E_top[1], E_top[2], E_top[3])
    E_middle = (sx, sy-width, sx + width, sy-width)
    drawLine(E_middle[0], E_middle[1], E_middle[2],E_middle[3])
    E_bottom = (sx, sy - height, sx + width, sy - height)
    drawLine(E_bottom[0], E_bottom[1], E_bottom[2], E_bottom[3])
    glColor3f(0.5, 0.0, 0.0)
    sx, sy = (160, 440)
    height, width = (20, 10)
    R_left = (sx, sy, sx, sy - height)  # Plotting R
    drawLine(R_left[0], R_left[1], R_left[2], R_left[3])
    R_right = (sx + width, sy, sx + width, sy - width)
    drawLine(R_right[0], R_right[1], R_right[2], R_right[3])
    R_top = (sx, sy, sx + width, sy)
    drawLine(R_top[0], R_top[1], R_top[2], R_top[3])
    R_middle = (sx, sy - width, sx + width, sy - width)
    drawLine(R_middle[0], R_middle[1], R_middle[2], R_middle[3])
    R_diagonal = (sx, sy - width, sx + width, sy - height)
    drawLine(R_diagonal[0], R_diagonal[1], R_diagonal[2], R_diagonal[3])
    glColor3f(1.0, 0.5, 0.0)
    sx, sy = (180, 440)
    height, width, height_1 = (20,10,5)
    Y_left=(sx,sy,sx+height_1,sy-width)# Plotting Y
    drawLine(Y_left[0],Y_left[1],Y_left[2],Y_left[3])
    Y_right = (sx+width, sy, sx, sy - height)
    drawLine(Y_right[0], Y_right[1], Y_right[2], Y_right[3])
    glColor3f(1.0, 0.0, 0.5)
    sx, sy = (210, 440)
    height, width = (20, 10)
    C_left = (sx, sy, sx, sy - height)  # Plotting C
    drawLine(C_left[0], C_left[1], C_left[2], C_left[3])
    C_top = (sx, sy, sx + width, sy)
    drawLine(C_top[0], C_top[1], C_top[2], C_top[3])
    C_bottom = (sx, sy - height, sx + width, sy - height)
    drawLine(C_bottom[0], C_bottom[1], C_bottom[2], C_bottom[3])
    glColor3f(1.0, 0.5, 0.5)
    sx, sy = (230, 440)
    height, width = (20, 10)
    H_left = (sx, sy, sx, sy - height)# Plotting H
    drawLine(H_left[0], H_left[1], H_left[2], H_left[3])
    H_right = (sx + width, sy, sx + width, sy - height)
    drawLine(H_right[0], H_right[1], H_right[2], H_right[3])
    H_middle = (sx, sy - width, sx + width, sy - width)
    drawLine(H_middle[0], H_middle[1], H_middle[2], H_middle[3])
    glColor3f(1.0, 0.5, 0.0)
    sx, sy = (250, 440)
    height, width = (20, 10)
    A_left = (sx, sy, sx, sy - height)  # Plotting A
    drawLine(A_left[0], A_left[1], A_left[2], A_left[3])
    A_right = (sx + width, sy, sx + width, sy - height)
    drawLine(A_right[0], A_right[1], A_right[2], A_right[3])
    A_top = (sx, sy, sx + width, sy)
    drawLine(A_top[0], A_top[1], A_top[2], A_top[3])
    A_middle = (sx, sy - width, sx + width, sy - width)
    drawLine(A_middle[0], A_middle[1], A_middle[2], A_middle[3])
    glColor3f(1.0, 0.0, 0.5)
    sx, sy = (270, 440)
    height, width = (20, 10)
    M_left = (sx, sy, sx, sy - height)  # Plotting M
    drawLine(M_left [0], M_left [1],M_left [2], M_left [3])
    M_right = (sx + height, sy, sx + height, sy - height)
    drawLine(M_right[0], M_right[1], M_right[2], M_right[3])
    M_middle = (sx+width, sy, sx +width, sy - height)
    drawLine(M_middle[0], M_middle[1], M_middle[2], M_middle[3])
    M_top = (sx , sy, sx + height, sy )
    drawLine(M_top[0], M_top[1], M_top[2], M_top[3])
    glColor3f(1.0, 0.5, 0.5)
    sx, sy = (300, 440)
    height, width = (20, 10)
    P_left = (sx, sy, sx, sy - height)# Plotting P
    drawLine(P_left[0], P_left[1], P_left[2], P_left[3])
    P_right = (sx+width , sy, sx + width, sy-width)
    drawLine(P_right[0], P_right[1], P_right[2], P_right[3])
    P_top= (sx , sy, sx + width, sy )
    drawLine(P_top[0], P_top[1], P_top[2], P_top[3])
    P_middle = (sx, sy-width, sx + width, sy-width)
    drawLine(P_middle[0], P_middle[1], P_middle[2], P_middle[3])
    glColor3f(0.0, 0.0, 1.0)
    sx, sy = (320, 440)
    height, width = (20, 10)
    I = (sx, sy, sx, sy - height)# Plotting I
    drawLine(I[0], I[1], I[2], I[3])
    glColor3f(1.0, 0.0, 0.5)
    sx, sy = (330, 440)
    height, width = (20, 10)
    C_left = (sx, sy, sx, sy - height)  # Plotting C
    drawLine(C_left[0], C_left[1], C_left[2], C_left[3])
    C_top = (sx, sy, sx + width, sy)
    drawLine(C_top[0], C_top[1], C_top[2], C_top[3])
    C_bottom = (sx, sy - height, sx + width, sy - height)
    drawLine(C_bottom[0], C_bottom[1], C_bottom[2], C_bottom[3])
    C_right = (sx+width, sy, sx + width, sy - height)
    drawLine(C_right[0], C_right[1], C_right[2], C_right[3])
    glColor3f(1.0, 0.5, 1.0)
    sx, sy = (350, 440)
    height, width = (20, 10)
    N_left = (sx, sy, sx, sy - height)  # Plotting N
    drawLine(N_left[0], N_left[1], N_left[2], N_left[3])
    N_middle = (sx, sy, sx + width, sy-height)
    drawLine(N_middle[0], N_middle[1], N_middle[2], N_middle[3])
    C_right = (sx + width, sy, sx + width, sy - height)
    drawLine(C_right[0], C_right[1], C_right[2], C_right[3])
    glColor3f(1.0, 0.5, 0.0)
    sx, sy = (370, 440)
    height, width = (20, 10)
    S_left = (sx, sy, sx, sy - width)  # Plotting S
    drawLine(S_left[0], S_left[1], S_left[2], S_left[3])
    S_top = (sx, sy, sx + width, sy)
    drawLine(S_top[0], S_top[1], S_top[2], S_top[3])
    S_middle = (sx, sy-width, sx + width, sy - width)
    drawLine(S_middle[0], S_middle[1], S_middle[2], S_middle[3])
    S_right = (sx + width, sy-width, sx + width, sy - height)
    drawLine(S_right[0], S_right[1], S_right[2], S_right[3])
    S_bottom = (sx, sy - height, sx + width, sy - height)
    drawLine(S_bottom[0], S_bottom[1], S_bottom[2], S_bottom[3])
    glColor3f(1.0, 0.0, 1.0)
    sx, sy = (390, 440)
    height, width = (20, 10)
    H_left = (sx, sy, sx, sy - height)# Plotting H
    drawLine(H_left[0], H_left[1], H_left[2], H_left[3])
    H_right = (sx + width, sy, sx + width, sy - height)
    drawLine(H_right[0], H_right[1], H_right[2], H_right[3])
    H_middle = (sx, sy - width, sx + width, sy - width)
    drawLine(H_middle[0], H_middle[1], H_middle[2], H_middle[3])
    glColor3f(1.0, 1.0, 0.0)
    sx, sy = (410, 440)
    height, width = (20, 10)
    I = (sx, sy, sx, sy - height)# Plotting I
    drawLine(I[0], I[1], I[2], I[3])
    glColor3f(1.0, 0.0, 0.5)
    sx, sy = (420, 440)
    height, width = (20, 10)
    P_left = (sx, sy, sx, sy - height)# Plotting P
    drawLine(P_left[0], P_left[1], P_left[2], P_left[3])
    P_right = (sx + width, sy, sx + width, sy - width)
    drawLine(P_right[0], P_right[1], P_right[2], P_right[3])
    P_top = (sx, sy, sx + width, sy)
    drawLine(P_top[0], P_top[1], P_top[2], P_top[3])
    P_middle = (sx, sy - width, sx + width, sy - width)
    drawLine(P_middle[0], P_middle[1], P_middle[2], P_middle[3])
    glColor3f(0.0, 1.0, 0.0)
    sx, sy = (450, 440)
    height, width = (20, 10)
    two_left = (sx , sy - width, sx , sy - height,)  # Plotting 2
    drawLine(two_left[0],two_left[1], two_left[2], two_left[3])
    two_top = (sx, sy, sx + width, sy)
    drawLine(two_top[0], two_top[1],two_top[2], two_top[3])
    two_middle = (sx, sy - width, sx + width, sy - width)
    drawLine(two_middle[0],two_middle[1],two_middle[2], two_middle[3])
    two_right = (sx+width, sy, sx+width, sy - width)
    drawLine(two_right[0], two_right[1], two_right[2], two_right[3])
    two_bottom = (sx, sy - height, sx + width, sy - height)
    drawLine(two_bottom[0], two_bottom[1], two_bottom[2], two_bottom[3])
    glColor3f(1.0, 1.0, 0.0)
    sx, sy = (470, 440)
    height, width = (20, 10)
    three_right = (sx+width, sy, sx+width, sy - height)  # Plotting 3
    drawLine(three_right[0], three_right[1], three_right[2], three_right[3])
    three_top = (sx, sy, sx + width, sy)
    drawLine(three_top[0], three_top[1], three_top[2],three_top[3])
    three_middle = (sx, sy - width, sx + width, sy - width)
    drawLine(three_middle[0], three_middle[1], three_middle[2], three_middle[3])
    three_bottom = (sx, sy - height, sx + width, sy - height)
    drawLine(three_bottom [0], three_bottom [1], three_bottom [2], three_bottom [3])