from OpenGL.GL import *
from OpenGL.GLUT import *
from OpenGL.GLU import *
from midpoint_line import *

def scoreBoard():
    glColor3f(1.0, 1.0, 0.0)
    sx,sy=(200,120)
    height,width,=(200,200)
    Score_box_left=(sx,sy,sx,sy-height)#Score_box Plotting
    drawLine(Score_box_left[0],Score_box_left[1],Score_box_left[2],Score_box_left[3])
    Score_box_right=(sx+height,sy,sx+height,sy-height)
    drawLine(Score_box_right[0], Score_box_right[1], Score_box_right[2], Score_box_right[3])
    Score_box_top = (sx,sy,sx+height,sy)#Box Plotting
    drawLine(Score_box_top[0], Score_box_top[1], Score_box_top[2], Score_box_top[3])
    Score_box_bottom = (sx, sy-height,sx+height,sy-height)
    drawLine(Score_box_bottom[0], Score_box_bottom[1], Score_box_bottom[2], Score_box_bottom[3])
    sx, sy = (210, 90)
    height, width,width_1,height_1 = 10, 20,25,50
    S_left = (sx, sy, sx, sy - width_1)  # Plotting S
    drawLine(S_left[0], S_left[1], S_left[2], S_left[3])
    S_top = (sx, sy, sx + height, sy)
    drawLine(S_top[0], S_top[1], S_top[2], S_top[3])
    S_middle = (sx, sy - width_1, sx +height, sy - width_1)
    drawLine(S_middle[0], S_middle[1], S_middle[2], S_middle[3])
    S_right = (sx + height, sy - width_1, sx + height, sy - height_1)
    drawLine(S_right[0], S_right[1], S_right[2], S_right[3])
    S_bottom = (sx, sy - height_1, sx + height, sy - height_1)
    drawLine(S_bottom[0], S_bottom[1], S_bottom[2], S_bottom[3])
    sx, sy = (230, 90)
    height, width,width_1,height_1 =(10, 20,25,50)
    C_left = (sx, sy, sx, sy - height_1)  # Plotting C
    drawLine(C_left[0], C_left[1], C_left[2], C_left[3])
    C_top = (sx, sy, sx + height, sy)
    drawLine(C_top[0], C_top[1], C_top[2], C_top[3])
    C_bottom = (sx, sy - height_1, sx + height, sy - height_1)
    drawLine(C_bottom[0], C_bottom[1], C_bottom[2], C_bottom[3])
    sx, sy = (250, 90)
    height, width,width_1,height_1 =(10, 20,25,50)
    O_left = (sx, sy, sx, sy - height_1)  # Plotting C
    drawLine(O_left[0], O_left[1], O_left[2], O_left[3])
    O_top = (sx, sy, sx + height, sy)
    drawLine(O_top[0], O_top[1], O_top[2], O_top[3])
    O_bottom = (sx, sy - height_1, sx + height, sy - height_1)
    drawLine(O_bottom[0], O_bottom[1], O_bottom[2], O_bottom[3])
    O_right = (sx + height, sy, sx + height, sy - height_1)
    drawLine(O_right[0], O_right[1], O_right[2], O_right[3])
    sx, sy = (270, 90)
    height, width, width_1, height_1 = (10, 20, 25, 50)
    R_left = (sx, sy, sx, sy - height_1)  # Plotting R
    drawLine(R_left[0], R_left[1], R_left[2], R_left[3])
    R_right = (sx + height, sy, sx + height, sy - width_1)
    drawLine(R_right[0], R_right[1], R_right[2], R_right[3])
    R_top = (sx, sy, sx + height, sy)
    drawLine(R_top[0], R_top[1], R_top[2], R_top[3])
    R_middle = (sx, sy - width_1, sx + height, sy - width_1)
    drawLine(R_middle[0], R_middle[1], R_middle[2], R_middle[3])
    R_diagonal = (sx, sy - width_1, sx + height, sy - height_1)
    drawLine(R_diagonal[0], R_diagonal[1], R_diagonal[2], R_diagonal[3])
    sx, sy = (290, 90)
    height, width, width_1, height_1 = (10, 20, 25, 50)
    E_left = (sx, sy, sx, sy - height_1)  # Plotting E
    drawLine(E_left[0], E_left[1], E_left[2], E_left[3])
    E_top = (sx, sy, sx + height, sy)
    drawLine(E_top[0], E_top[1], E_top[2], E_top[3])
    E_middle = (sx, sy - width_1, sx + height, sy - width_1)
    drawLine(E_middle[0], E_middle[1], E_middle[2], E_middle[3])
    E_bottom = (sx, sy - height_1, sx + height, sy - height_1)
    drawLine(E_bottom[0], E_bottom[1], E_bottom[2], E_bottom[3])
    sx, sy = (320, 90)
    height, width, width_1, height_1,height_2,width_2 = (10, 20, 25, 50,5,30)
    c1_left = (sx, sy-width_1, sx, sy - width_2)  # Plotting C1
    drawLine(c1_left[0], c1_left[1], c1_left[2], c1_left[3])
    c1_top = (sx, sy-width_1, sx + height, sy-width_1)
    drawLine(c1_top[0], c1_top[1], c1_top[2], c1_top[3])
    c1_bottom = (sx, sy - width_2, sx + height, sy - width_2)
    drawLine(c1_bottom[0], c1_bottom[1], c1_bottom[2], c1_bottom[3])
    c1_right = (sx + height, sy-width_1, sx + height, sy - width_2)
    drawLine(c1_right[0], c1_right[1], c1_right[2], c1_right[3])
    sx, sy = (320, 90)
    height, width, width_1, height_1, height_2, width_2,height_3 ,width_3= (10, 20, 25, 50, 5, 30,45,40)
    c1_left = (sx, sy - width_3, sx, sy - height_3)  # Plotting C2
    drawLine(c1_left[0], c1_left[1], c1_left[2], c1_left[3])
    c1_top = (sx, sy - width_3, sx + height, sy - width_3)
    drawLine(c1_top[0], c1_top[1], c1_top[2], c1_top[3])
    c1_bottom = (sx, sy - height_3, sx + height, sy - height_3)
    drawLine(c1_bottom[0], c1_bottom[1], c1_bottom[2], c1_bottom[3])
    c1_right = (sx + height, sy - width_3, sx + height, sy - height_3)
    drawLine(c1_right[0], c1_right[1], c1_right[2], c1_right[3])
